version: "2"
services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: admin
      MYSQL_ROOT_PASSWORD: password
  wordpress:
    container_name: wordpress
    image: wordpress:4.6.1-apache
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8000:80
    volumes:
      - ./.plugins:/var/www/html/wp-content/plugins
      - ./theme:/var/www/html/wp-content/themes/friends-dinner
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: password
